# Generated by Django 4.2.30 on 2026-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productmodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
